#!/bin/bash
# mkdisk: create a virtual disk diskimage

# Gets current actual user instead of root
CURRENTUSER=$(who | awk 'NR==1{print $1}')

# create disk image
dd if=/dev/zero of=diskimage bs=1024 count=1440
mke2fs -b 1024 diskimage 1440

# mount it inside cwd's mnt dir
mount diskimage mount

# Create files
#(cd /mnt; sudo mkdir dir1 dir2 dir1/dir3; sudo touch file1 file2; ls -l)

# Change disk owner to current user
chown $CURRENTUSER:$CURRENTUSER -R mount

# unmount
umount mount

