#!/bin/bash
# mkdisk: create a virtual disk diskimage

dd if=/dev/zero of=diskimage bs=1024 count=1440
mke2fs -b 1024 diskimage 1440

mount diskimage mnt/

#(cd /mnt; sudo mkdir dir1 dir2 dir1/dir3; sudo touch file1 file2; ls -l)
chown $USER:$USER -R mnt/

umount mnt/

